exclude = [
    ".bzr",
    ".cadence",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    "*.ipynb",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]


lint.select = [
    'I', 'F', 'E', 'W', 'C90', 'N', 'ASYNC', 'B', 'A',
    'ISC', 'ICN', 'G', 'PIE', 'PYI', 'INP', 'Q', 'RSE',
    'SLF', 'SIM', 'TID', 'INT', 'PD', 'PLE',
    'PLR', 'PLW', 'FLY', 'RUF'
]
lint.ignore = ["RUF005", "B905", "PLR0913", "PLR2004", "G004", "SIM108", "SIM118", "RUF012"]
line-length = 120
lint.pycodestyle.max-line-length = 140
target-version = "py38"

[lint.isort]
known-third-party = ["wandb"]

[lint.flake8-quotes]
inline-quotes = "double"

[lint.flake8-annotations]
mypy-init-return = false