wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1733408202.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      3:
      - 5
      - 7
      - 13
      - 23
      - 62
      4: 3.8.13
      5: 0.16.6
      6: 4.40.1
      8:
      - 5
      9:
        1: transformers_trainer
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/accuracy
      5: 1
      6:
      - 1
    - 1: eval/f1
      5: 1
      6:
      - 1
    - 1: eval/combined_score
      5: 1
      6:
      - 1
    - 1: eval/accuracy_10
      5: 1
      6:
      - 1
    - 1: eval/accuracy_11
      5: 1
      6:
      - 1
    - 1: eval/accuracy_12
      5: 1
      6:
      - 1
    - 1: eval/accuracy_13
      5: 1
      6:
      - 1
    - 1: eval/accuracy_14
      5: 1
      6:
      - 1
    - 1: eval/accuracy_15
      5: 1
      6:
      - 1
    - 1: eval/accuracy_16
      5: 1
      6:
      - 1
    - 1: eval/accuracy_17
      5: 1
      6:
      - 1
    - 1: eval/accuracy_18
      5: 1
      6:
      - 1
    - 1: eval/accuracy_19
      5: 1
      6:
      - 1
    - 1: eval/accuracy_20
      5: 1
      6:
      - 1
    - 1: eval/accuracy_21
      5: 1
      6:
      - 1
    - 1: eval/accuracy_22
      5: 1
      6:
      - 1
    - 1: eval/accuracy_23
      5: 1
      6:
      - 1
    - 1: eval/accuracy_24
      5: 1
      6:
      - 1
    - 1: eval/accuracy_25
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
seed:
  desc: null
  value: 0
tf32:
  desc: null
  value: null
debug:
  desc: null
  value: []
optim:
  desc: null
  value: adamw_torch
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
prefix:
  desc: null
  value: null
do_eval:
  desc: null
  value: true
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
do_train:
  desc: null
  value: true
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    not_equivalent: 0
    equivalent: 1
run_name:
  desc: null
  value: results_mrpc_25
use_ipex:
  desc: null
  value: false
adafactor:
  desc: null
  value: false
data_seed:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
do_sample:
  desc: null
  value: false
hub_token:
  desc: null
  value: <HUB_TOKEN>
log_level:
  desc: null
  value: passive
max_steps:
  desc: null
  value: -1
num_beams:
  desc: null
  value: 1
ray_scope:
  desc: null
  value: last
report_to:
  desc: null
  value:
  - tensorboard
  - wandb
typical_p:
  desc: null
  value: 1.0
use_cache:
  desc: null
  value: true
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
do_predict:
  desc: null
  value: false
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: null
hidden_act:
  desc: null
  value: gelu
is_decoder:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: roberta
optim_args:
  desc: null
  value: null
output_dir:
  desc: null
  value: results_mrpc_25/roberta-large/mrpc/pretrained_LoRA_init_svd_rank_25_lr_0.001_clsLR_0.0006_seed_0/last
past_index:
  desc: null
  value: -1
save_steps:
  desc: null
  value: 1000000
vocab_size:
  desc: null
  value: 50265
ddp_backend:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
hidden_size:
  desc: null
  value: 1024
label_names:
  desc: null
  value: null
logging_dir:
  desc: null
  value: results_mrpc_25/runs/Dec05_15-15-44_mallahova
push_to_hub:
  desc: null
  value: false
return_dict:
  desc: null
  value: true
temperature:
  desc: null
  value: 1.0
torch_dtype:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
adam_epsilon:
  desc: null
  value: 1.0e-08
bos_token_id:
  desc: null
  value: 0
disable_tqdm:
  desc: null
  value: false
eos_token_id:
  desc: null
  value: 2
fp16_backend:
  desc: null
  value: auto
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
pad_token_id:
  desc: null
  value: 1
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
sep_token_id:
  desc: null
  value: null
use_bfloat16:
  desc: null
  value: false
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
_name_or_path:
  desc: null
  value: roberta-large
architectures:
  desc: null
  value:
  - RobertaForMaskedLM
bad_words_ids:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
logging_steps:
  desc: null
  value: 20
max_grad_norm:
  desc: null
  value: 1.0
mp_parameters:
  desc: null
  value: ''
output_scores:
  desc: null
  value: false
save_strategy:
  desc: null
  value: steps
split_batches:
  desc: null
  value: null
torch_compile:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
bf16_full_eval:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
layer_norm_eps:
  desc: null
  value: 1.0e-05
length_penalty:
  desc: null
  value: 1.0
tf_legacy_loss:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
finetuning_task:
  desc: null
  value: mrpc
group_by_length:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
num_beam_groups:
  desc: null
  value: 1
save_only_model:
  desc: null
  value: false
suppress_tokens:
  desc: null
  value: null
tokenizer_class:
  desc: null
  value: null
type_vocab_size:
  desc: null
  value: 1
dispatch_batches:
  desc: null
  value: null
full_determinism:
  desc: null
  value: false
hub_private_repo:
  desc: null
  value: false
ignore_data_skip:
  desc: null
  value: false
log_on_each_node:
  desc: null
  value: true
logging_strategy:
  desc: null
  value: steps
num_train_epochs:
  desc: null
  value: 120.0
save_safetensors:
  desc: null
  value: true
save_total_limit:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
diversity_penalty:
  desc: null
  value: 0.0
greater_is_better:
  desc: null
  value: null
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 4096
log_level_replica:
  desc: null
  value: warning
lr_scheduler_type:
  desc: null
  value: linear
num_hidden_layers:
  desc: null
  value: 24
output_attentions:
  desc: null
  value: false
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
save_on_each_node:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    gradient_accumulation_kwargs: null
classifier_dropout:
  desc: null
  value: null
is_encoder_decoder:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
logging_first_step:
  desc: null
  value: false
repetition_penalty:
  desc: null
  value: 1.0
torch_compile_mode:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: epoch
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fsdp_min_num_params:
  desc: null
  value: 0
hidden_dropout_prob:
  desc: null
  value: 0.1
lr_scheduler_kwargs:
  desc: null
  value: {}
neftune_noise_alpha:
  desc: null
  value: null
num_attention_heads:
  desc: null
  value: 16
skip_memory_metrics:
  desc: null
  value: true
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
auto_find_batch_size:
  desc: null
  value: false
dataloader_drop_last:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_return_sequences:
  desc: null
  value: 1
optim_target_modules:
  desc: null
  value: null
output_hidden_states:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
prediction_loss_only:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
transformers_version:
  desc: null
  value: 4.40.1
begin_suppress_tokens:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
ddp_broadcast_buffers:
  desc: null
  value: null
metric_for_best_model:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
torch_compile_backend:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
decoder_start_token_id:
  desc: null
  value: null
eval_do_concat_batches:
  desc: null
  value: true
gradient_checkpointing:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
label_smoothing_factor:
  desc: null
  value: 0.0
load_best_model_at_end:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
resume_from_checkpoint:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
eval_accumulation_steps:
  desc: null
  value: null
max_position_embeddings:
  desc: null
  value: 514
per_gpu_eval_batch_size:
  desc: null
  value: null
position_embedding_type:
  desc: null
  value: absolute
return_dict_in_generate:
  desc: null
  value: false
per_gpu_train_batch_size:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
dataloader_prefetch_factor:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
per_device_eval_batch_size:
  desc: null
  value: 8
use_legacy_prediction_loop:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
per_device_train_batch_size:
  desc: null
  value: 11
attention_probs_dropout_prob:
  desc: null
  value: 0.1
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
dataloader_persistent_workers:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_num_input_tokens_seen:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
